@startuml

main --> StockController: getFinInfo()
    StockController --> ScrapeStockInfo: getStockLinks()
    ScrapeStockInfo --> StockController: vector<string>: Links
    StockController --> ScrapeStockInfo: getStockInfo(vector<string> links)
    ScrapeStockInfo --> StockController: StockInfo
    StockController --> StockController: makeRespMsg(vector<StockInfo>)
StockController --> main: string

@enduml